// User
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_UER = "REGISTER_UER";

// Movie
export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_MOVIES_DETAIL = "GET_MOVIES_DETAIL";

// TV Show
